tasks:
  - init: yarn
    command: |
      gp open src/App.svelte
      yarn snowpack dev
ports:
  - port: 8080
    onOpen: open-preview
vscode:
  extensions:
    - svelte.svelte-vscode
    - bradlc.vscode-tailwindcss
    - esbenp.prettier-vscode